# Generated by Django 3.1.1 on 2021-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcryption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
